### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by adibbley** [comment]
CI error on linux:
```
Failed to load Qt platform plugin: "xcb"
 - Library path: $PREFIX/nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/Plugins/platforms/libqxcb.so
 - Error: libxcb-cursor.so.0: cannot open shared object file: No such file or directory
```
Looks to be resolved by adding `xcb-util-cursor`

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please restart CI

(Azure didn't run previously. So try to start CI again)

**Comment by jakirkham** [comment]
Azure is running now

**Pull request merged**
